language: node_js
node_js:
  - '9'
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - binutils-2.26
env:
  - CC=gcc-7 CXX=g++-7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libglfw-dev libglew-dev
install:
  - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
  - npm install
notifications:
  slack: exokit:ZezcBTTBFxiGDGOhRSrtWKOJ
