language: node_js
node_js:
- '9'
os:
- osx
before_install:
- brew install glfw glew
install:
- npm install
- tar -czf exokit-macos.tar.gz --exclude=".*" *
deploy:
  provider: releases
  api_key:
    secure: aCVZI0mi3BU9mo7eDXbrQMPSxp/RL0FH1sZ15H+7aTsT0xu66StFR8fp2SQjWRZS+IVWXIXkvlcp0ND4GCmyEEfQMnRLPaXqCV1OujwbWESUZUWn4a76+RVV8zuNSSEMWMtjYOdpUyCGiu3cjbExKaoAFMy5aYAzCTggERqZNfMMZsmYkH3mAzWCYOmHuVYVqmwgjdjsA2ziP227TW4aHCewFDJjVZn5zaWZhfWccDEFvTiZY08QHr1cZYNr11qFG9YnPtr0KeXqOXggKzwO0BQGRwacvd2wLggMyKUkYgsaslIPNIAn1EcLtaN5JDSRef5cL3aIGCJw1RHoc2QgwTOrA7OCHp81g7ciExQpMv2yz4jtETmEdETtjaZM2BE3zjKFVvWKWeQAHVHHzeCUyYUk1zexJMWy1uskS16+Pj2KUSSMHq9GoEwU9p8yz/fO+/ANQCYfbI21rzSj3OIGnZgIAePG+NbhN3FCZv6M+QFyOxzQ3gkI/sUc/6EXDDjfN+RFJXQfT1QBDYWOmkxSJj6f6DnZdnu4eBru+R7kb/DKTmsKxHF4u0Gw1qye8U7fqENyKpqNXLSmU0PWdJ4a1PwHyIYefuXKy0rWBZKZBIVsBOnethjDgYGi+Mfe7PlREmb0iTnDzAlizcntMFCQt1eTsi6bmJogXfuv6G6Zc2c=
  file: 'exokit-macos.tar.gz'
  body: "Exokit macOS git release"
  on:
    repo: modulesio/exokit-macos
    tags: true
  skip_cleanup: true
notifications:
  slack: exokit:ZezcBTTBFxiGDGOhRSrtWKOJ
