language: node_js
node_js:
- '9'
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - binutils-2.26
    env:
    - CC=gcc-7 CXX=g++-7
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y libglfw-dev libglew-dev
    install:
    - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
    - npm install
    - wget "https://nodejs.org/dist/v9.7.1/node-v9.7.1-linux-x64.tar.gz" -O node.tar.gz
    - tar -zxf node.tar.gz
    - rm node.tar.gz
    - mv "node-v9.7.1-linux-x64" node
    - tar -czf exokit-linux.tar.gz --exclude=".*" *
    deploy:
      provider: releases
      api_key:
        secure: kEIjaNjqi4lnHMePkebADeLzEiw9fZXr6tCs8+eTyB81Y55M8NrySygT4CTBg4Reb0GWJ+0lYyoQbFYc+ZTJ1q+JrBMMwWCE5ie65/4UOlond/2oIt6CUUavKoHq8JC5+WvpBpPGN0jYgxZyusmZIDLZ4mHJfnoUzizUyCmaybZKMVeOqhgHyfHgfp4hAnd00WGfbGPju49vjCMwQI0ErRoG/xL7qfSSl8q7Ke6Rx/sgFo1eVkhOHziv/bnu3DrkrhcUn7obG2o1mpQZBBCH3pXTfDmxr/WeLeq4wNfXdPlUhyXxduoi+34QavyZ7eRl6nzQLFRLEWwrGNIztWPRA8UShpNjWPM/wRXxoUzZAidN6YMrtSe3Bp/+PvJxYhfNPiKqJZhThwK/KYSXBKkLQGJFTtqmFdrBPQqjp+XrXzASO6khtMuCrmNhU8lZBVdc9LQ8aLP27FI68NIsHEHZBkSPoNT4MHyjjdhVwb1yg3jlMWDhZNAEWymJHt9vtDzh59R/JurpgRrhsZV9Yuoakb5cEX/jwTYrolvX7eT9/e/D1AYGybuSBw+Qp2/0lqOJhRXEiVj1P7VppmPe6krcagxftbhI8uA7VkvSieS7HhdzuBY5Lq9YDebgYztw5C6Jp7omnkpWGLOfmhOG4dFHSIzIVCDd+S9bm16ign6Eob8=
      file: exokit-linux.tar.gz
      body: Exokit git release
      on:
        repo: modulesio/exokit
        tags: true
      skip_cleanup: true
  - os: osx
    before_install:
    - brew install glfw glew
    install:
    - npm install
    - curl "https://nodejs.org/dist/v9.7.0/node-v9.7.0-darwin-x64.tar.gz" >node.tar.gz
    - tar -zxf node.tar.gz
    - rm node.tar.gz
    - mv "node-v9.7.0-darwin-x64" node
    - tar -czf exokit-macos.tar.gz --exclude=".*" *
    deploy:
      provider: releases
      api_key:
        secure: kEIjaNjqi4lnHMePkebADeLzEiw9fZXr6tCs8+eTyB81Y55M8NrySygT4CTBg4Reb0GWJ+0lYyoQbFYc+ZTJ1q+JrBMMwWCE5ie65/4UOlond/2oIt6CUUavKoHq8JC5+WvpBpPGN0jYgxZyusmZIDLZ4mHJfnoUzizUyCmaybZKMVeOqhgHyfHgfp4hAnd00WGfbGPju49vjCMwQI0ErRoG/xL7qfSSl8q7Ke6Rx/sgFo1eVkhOHziv/bnu3DrkrhcUn7obG2o1mpQZBBCH3pXTfDmxr/WeLeq4wNfXdPlUhyXxduoi+34QavyZ7eRl6nzQLFRLEWwrGNIztWPRA8UShpNjWPM/wRXxoUzZAidN6YMrtSe3Bp/+PvJxYhfNPiKqJZhThwK/KYSXBKkLQGJFTtqmFdrBPQqjp+XrXzASO6khtMuCrmNhU8lZBVdc9LQ8aLP27FI68NIsHEHZBkSPoNT4MHyjjdhVwb1yg3jlMWDhZNAEWymJHt9vtDzh59R/JurpgRrhsZV9Yuoakb5cEX/jwTYrolvX7eT9/e/D1AYGybuSBw+Qp2/0lqOJhRXEiVj1P7VppmPe6krcagxftbhI8uA7VkvSieS7HhdzuBY5Lq9YDebgYztw5C6Jp7omnkpWGLOfmhOG4dFHSIzIVCDd+S9bm16ign6Eob8=
      file: exokit-macos.tar.gz
      body: Exokit git release
      on:
        repo: modulesio/exokit
        tags: true
      skip_cleanup: true
notifications:
  slack: exokit:ZezcBTTBFxiGDGOhRSrtWKOJ
