language: node_js
node_js:
  - '9'
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libglfw-dev libglew-dev
notifications:
  slack: exokit:ZezcBTTBFxiGDGOhRSrtWKOJ
