language: node_js
node_js:
- '9'
matrix:
  include:
  - os: linux
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - gcc-7
        - g++-7
        - binutils-2.26
    env:
    - CC=gcc-7 CXX=g++-7
    before_install:
    - sudo apt-get update
    - sudo apt-get install -y libglfw-dev libglew-dev
    install:
    - export PATH=/usr/lib/binutils-2.26/bin:${PATH}
    - npm install
    - wget "https://nodejs.org/dist/v9.8.0/node-v9.8.0-linux-x64.tar.gz" -O node.tar.gz
    - tar -zxf node.tar.gz
    - rm node.tar.gz
    - mv "node-v9.8.0-linux-x64" node
    - tar -czf exokit-linux.tar.gz --exclude=".*" *
    deploy:
      provider: releases
      api_key:
        secure: OlejFsEjiEBzw44wFRlmQb3stF+PURu52AMogc1t4qu54x6YRxxk0NMlv3nzGlObo9JnOPMhAfISgDr8515jqvGEfFXcDzFOPIx42nyqVZe0I8UCA4cRbsV3EvvXtYfbwaXa9n65kk+RuEJEdtqEAWy9xYjiJGDhtkKv2khVDIVhrS6fbleHGanNcFlYsOzyf7ZWouFq4wIEX+ovNhe2hRZKRjzgKnFcPaKIzlG8qQF3WrdL0L4D2FE6xA4+lc56R2dKrpmvR9r32kRLS620apS0iFKOWwttgNiIf580RElmUGa+mTEi9Bob9pods0pcmLpWhhqRddPyi5G2PVgZG1FCaXdymwmS7FsNNo1sqvAmISuhcQrHNUMqmdYbpl7vvBHHmzXPIQjfxPU9zaPFEctW+wqmZUf+WuWJeZmQInCbUxe/bRS9OFQtRMiyzcdFvYfOtZg/Sv8/YeaihGff+n0k36Im3TPygsDLEaMBpTM4EXUd6TRk+631nUVQy/Z8WSzWwKWM2cCjRtMbKqDVy7M2vYBYQ1F9WlZidGUD5nYu1uNKsV7rfqpNsvagt7dQL8aJRQN0JgAKgRe8sKXUzl299JXTo+TdTUgqmkr4DoAoH6972JcdcT1mRK8B1oMjLFkB8oef9SbfOoBRKT17V65dZHTJEMhgKLQHrCpcbHE=
      file: exokit-linux.tar.gz
      body: Exokit git release
      on:
        repo: modulesio/exokit
        tags: true
      skip_cleanup: true
  - os: osx
    osx_image: xcode9.2
    before_install:
    - brew install glfw glew
    install:
    - npm install
    - curl "https://nodejs.org/dist/v9.8.0/node-v9.8.0-darwin-x64.tar.gz" >node.tar.gz
    - tar -zxf node.tar.gz
    - rm node.tar.gz
    - mv "node-v9.8.0-darwin-x64" node
    - tar -czf exokit-macos.tar.gz --exclude=".*" *
    deploy:
      provider: releases
      api_key:
        secure: OlejFsEjiEBzw44wFRlmQb3stF+PURu52AMogc1t4qu54x6YRxxk0NMlv3nzGlObo9JnOPMhAfISgDr8515jqvGEfFXcDzFOPIx42nyqVZe0I8UCA4cRbsV3EvvXtYfbwaXa9n65kk+RuEJEdtqEAWy9xYjiJGDhtkKv2khVDIVhrS6fbleHGanNcFlYsOzyf7ZWouFq4wIEX+ovNhe2hRZKRjzgKnFcPaKIzlG8qQF3WrdL0L4D2FE6xA4+lc56R2dKrpmvR9r32kRLS620apS0iFKOWwttgNiIf580RElmUGa+mTEi9Bob9pods0pcmLpWhhqRddPyi5G2PVgZG1FCaXdymwmS7FsNNo1sqvAmISuhcQrHNUMqmdYbpl7vvBHHmzXPIQjfxPU9zaPFEctW+wqmZUf+WuWJeZmQInCbUxe/bRS9OFQtRMiyzcdFvYfOtZg/Sv8/YeaihGff+n0k36Im3TPygsDLEaMBpTM4EXUd6TRk+631nUVQy/Z8WSzWwKWM2cCjRtMbKqDVy7M2vYBYQ1F9WlZidGUD5nYu1uNKsV7rfqpNsvagt7dQL8aJRQN0JgAKgRe8sKXUzl299JXTo+TdTUgqmkr4DoAoH6972JcdcT1mRK8B1oMjLFkB8oef9SbfOoBRKT17V65dZHTJEMhgKLQHrCpcbHE=
      file: exokit-macos.tar.gz
      body: Exokit git release
      on:
        repo: modulesio/exokit
        tags: true
      skip_cleanup: true
notifications:
  slack: exokit:ZezcBTTBFxiGDGOhRSrtWKOJ
