version: 0.0.{build}

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "9"
  MAGICLEAP:
    secure: 4mAodSQiCUr1X1maLOYyj4nYCb87r4J54Wb1jw1EE9tT4tpcbic6hpDynrSu7Ep3

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

after_test:
  - ps: |
      npm install
      7z a exokit-windows.zip * -xr'!.git'
      wget "https://nodejs.org/download/nightly/v10.0.0-nightly2018040808a36a0666/node-v10.0.0-nightly2018040808a36a0666-win-x64.zip" -OutFile node.zip
      7z x node.zip
      rm node.zip
      mv "node-v9.8.0-win-x64" node
      rm -R node/node_modules
      7z a exokit-windows-full.zip * -xr'!.git'

artifacts:
  - path: "exokit-windows.zip"
    name: exokit-windows
  - path: "exokit-windows-full.zip"
    name: exokit-windows-full

deploy:
  - provider: GitHub
    description: 'Exokit git release'
    auth_token:
      secure: JzzhsoEKVJ6oKuS/3Uwa+odltY7CFRU/V5BaO62rG6BwfSeCydMDX5o/gJScQGkN
    artifact: "exokit-windows.zip"
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: GitHub
    description: 'Exokit git release'
    auth_token:
      secure: JzzhsoEKVJ6oKuS/3Uwa+odltY7CFRU/V5BaO62rG6BwfSeCydMDX5o/gJScQGkN
    artifact: "exokit-windows-full.zip"
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true

notifications:
  - provider: Slack
    auth_token:
      secure: 45CGZx1wukHisNzZTeLLraViNfOZxzzjx5lCfcrBq57T+fCPvD0UkJ0v3Slc/ykJ6TL5feuLnp0CGrAwtlfNztcTdPNlpCkGuWskq1A+Ehw=
    channel: '#builds'

# Don't actually build.
build: off
