version: 0.0.{build}

# branches to build
branches:
  # whitelist
  only:
    - master

# Test against the latest version of this Node.js version
environment:
  nodejs_version: "9"

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version x64

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

after_test:
  - ps: |
      git submodule update --init --recursive
      npm i
      7z a exokit.zip * -xr'!.git'

artifacts:
  - path: "exokit.zip"
    name: exokit

deploy:
  release: build-$(APPVEYOR_BUILD_NUMBER)
  description: 'Exokit git release'
  provider: GitHub
  auth_token:
    secure: JzzhsoEKVJ6oKuS/3Uwa+odltY7CFRU/V5BaO62rG6BwfSeCydMDX5o/gJScQGkN # your encrypted token from GitHub
  artifact: "exokit.zip"
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    # appveyor_repo_tag: true        # deploy on tag push only

notifications:
  - provider: Slack
    auth_token:
      secure: 45CGZx1wukHisNzZTeLLraViNfOZxzzjx5lCfcrBq57T+fCPvD0UkJ0v3Slc/ykJ6TL5feuLnp0CGrAwtlfNztcTdPNlpCkGuWskq1A+Ehw=
    channel: '#builds'

# Don't actually build.
build: off
